---
- name: Deletes the relevant user
  hosts: wanted
  vars_files:
    - vars.yml
  become: true
  #become_user: "{{ host_user }}"
  become_user: root

  tasks:

    - name: Ensure group simpliface exists
      ansible.builtin.group:
        name: "{{ host_groups }}"
        state: present
      when: 1 > 2

    - name: Remove user   host_user
      ansible.builtin.user:
        name: "{{ host_user }}"
        state: absent
        remove: true
      when: 1 > 0









