---
- name: analyse the nodes
  hosts: wanted
  become: yes

  tasks:

    - name: shell command
      shell: "/usr/bin/uname -a"
      register: myshell_output

    - name: copy the output to a local file
      copy:
        content: "{{ myshell_output.stdout_lines }}"
        dest: "/home/robert/node-info.txt"  #dest: "/home/robert/.simpli/logs/node-info.txt"
      delegate_to: localhost





