---
- name: Copy over the simpli tools and files. This does NOT configure the system. # Does not depend on anything
  hosts: wanted
  vars_files:
    - vars.yml
  become: true
  become_user: "{{ host_user }}"

  tasks:

    - name: 1. create local bin folders
      ansible.builtin.file:
        path: "{{ local_bin }}"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0775
      tags: copy

    - name: 2. create simpli folder
      ansible.builtin.file:
        path: "{{ simpli_dir }}"
        state: directory
        owner: "{{ host_user }}"
        group: "{{ host_user }}"
        mode: 0775
      become_user: "{{ host_user }}"
      tags: copy

    - name: 3A. create simpli sub folders
      ansible.builtin.file:
        path: "{{ simpli_dir }}/{{ item }}"
        state: directory
      become_user: "{{ host_user }}"
      loop:
        - info
        - config
        - media
        - utils
        - packages
        - logs
        - fish
      tags: copy

    - name: 3B. create home dir sub folders
      ansible.builtin.file:
        path: "{{ home_dir }}/{{ item }}"
        state: directory
      become_user: "{{ host_user }}"
      loop:
        - xDesktop
      tags: copy

    - name: 4. copy scripts to utils
      ansible.builtin.copy:
        src: "{{ src_deployment_dir }}/utils/"
        dest: "{{ simpli_utils_dir }}/"
        mode: 0775
      become_user: "{{ host_user }}"
      tags: copy

    - name: 5. link utils # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html
      ansible.builtin.shell:
        cmd: |
          /usr/bin/rm -f "{{ local_bin }}/{{ item.link_end }}"
          /usr/bin/ln -s "{{ simpli_dir }}/utils/{{ item.actual }}" "{{ local_bin }}/{{ item.link_end }}"
      become_user: "{{ host_user }}"
      loop:
        - { actual: 'know-device.sh', link_end: 'simpli-report' }
        - { actual: 'start-zoom.sh', link_end: 'simpli-zoom' }
        - { actual: 'vlc-watch.sh', link_end: 'simpli-watch' }
        - { actual: 'env_config.sh', link_end: 'simpli-config' }

    - name: 6A. update device info with node name
      ansible.builtin.shell:
        cmd: |
          echo 'Simpli Device info'
          echo '================== '
          echo 'HOSTNAME == {{ inventory_hostname }}'
          echo 'MAC == {{ clients[inventory_hostname].mac_wired }}'
          echo -n 'UNAME == '
          /usr/bin/uname -a 
          echo 'LINUX_USER == {{ clients[inventory_hostname].os_account }}'
          echo 'PERSON == {{ clients[inventory_hostname].person }}'
          echo 'COMMENT == {{ clients[inventory_hostname].comment }}'
          echo -n 'DEPLOY DATE == '
          /usr/bin/date
          echo 'ANSIBLE_HOSTNAME == {{ ansible_hostname }}'
          echo  'ANSIBLE_DATE_TIME == {{ ansible_date_time.iso8601 }}'
          echo ---
          echo
      register: command_output
      become_user: "{{ host_user }}"
      tags: report

    - name: 6B. Print output to file # '/home/robert/.simpli/info/dev-info.txt'
      ansible.builtin.copy:
        content: "{{ command_output.stdout }}"
        dest: "{{ device_info_file }}"
      become_user: "{{ host_user }}"
      tags: report

    - name: 7. remove utils in .local/bin - these are historical
      ansible.builtin.file:
        name: "{{ local_bin }}/{{ item }}"
        state: absent
      loop:
        - know-device.sh
        - startzoom.sh
        - vlc-watch.sh
        - report
        - simplireport
      when: False
      tags: copy

    - name: 10. copy Desktop related files e.g. png of icon
      ansible.builtin.copy:
        src: "{{ src_desktop_images }}/"
        dest: "{{ simpli_config_dir }}/"
      become_user: "{{ host_user }}"
      tags: copy

    - name: 11. copy config files
      ansible.builtin.copy:
        src: "{{ src_desktop_config }}/"
        dest: "{{ simpli_config_dir }}/"
      become_user: "{{ host_user }}"
      tags: copy

    - name: 11. copy Template file  It is questionable if this is needed
      ansible.builtin.copy:
        src: "{{ src_desktop_config }}/template.desktop/"
        dest: "{{ simpli_config_dir }}/info"
      become_user: "{{ host_user }}"
      tags: copy

    - name: 12. copy Media file
      ansible.builtin.copy:
        src: "{{ src_media_folder }}"
        dest: "{{ simpli_media_dir }}"
      become_user: "{{ host_user }}"
      tags: copy

    - name: 13A. generate report
      ansible.builtin.shell:
        cmd: '{{ simpli_utils_dir }}/know-device.sh show {{ clients[inventory_hostname].desktop }} '
      become_user: "{{ host_user }}"
      tags: report
      when: 1>0

    - name: 13B. perform initial check
      ansible.builtin.shell:
        cmd: '{{ simpli_utils_dir }}/know-device.sh check {{ clients[inventory_hostname].desktop }} '
      tags: report
      when: 1>2












