---
- name: update nodes
  hosts: wanted
  become: yes

  tasks:

    - name: 1. Install python
      apt:
        name: python3
        update_cache: yes

    - name: 2. Install python packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - python3-pip
        - python3-yaml
        - python3-psutil
        - python3-jinja2

    - name: 4. Install wanted tools
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - net-tools
        - curl
        - unzip
        - tree
        - xz-utils
        - meld
        - ncdu
        - dconf-editor
        - screenfetch
        - lightdm
        - vlc
      when: 1 > 0

    - name: 5. Remove unwanted tools
      apt:
        name: "{{ item }}"
        update_cache: yes
        status: "absent"
      loop:
        - thunderbird
        - libreoffice
      when: 1 > 2

    - name: 8. set desktop settings
      ansible.builtin.shell:
        cmd: "{{ simpli_dir }}/utils/set-desk.sh"
      when: 1 > 2

    - name: 9. Restart service lightdm
      ansible.builtin.service:
        name: lightdm
        enabled: yes
        state: restarted
      when: 1 > 2




