---
- name: Installs 3rd party components # Does not depend on simpli components
  hosts: wanted
  become: yes

  tasks:

    - name: 1. Remove unwanted tools
      apt:
        name: "{{ item }}"
        update_cache: yes
        status: "absent"
      loop:
        - thunderbird
        - libreoffice
      when: 1 > 2

    - name: 2. Install python # Is this necessary??
      apt:
        name: python3
        update_cache: yes

    - name: 3. Install python packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - python3-pip
        - python3-yaml
        - python3-psutil
        - python3-jinja2

    - name: 4. Install wanted tools
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - vim
        - net-tools
        - curl
        - eog
        - firefox
        - gedit
        - kphotoalbum
        - unzip
        - tree
        - xz-utils
        - meld
        - ncdu
        - dconf-editor
        - screenfetch
        - neofetch
        - vlc
      when: 1 > 0

    - name: 5. Install sound related packages # require reboot
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - pulseaudio
        - pavucontrol

    - name: 6. Install desktop related packages # Not sure this is needed
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - lightdm
      when: 1 > 2







