---
- name: Installs 3rd party components # Does not depend on simpli components
  hosts: wanted
  become: yes

  tasks:

    - name: 1. Remove unwanted tools
      apt:
        name: "{{ item }}"
        update_cache: yes
        status: "absent"
      loop:
        - thunderbird
        - libreoffice
      when: 1 > 2

    - name: 2. Install wanted tools
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - curl
        - dconf-editor
        - eog
        - firefox
        - gedit
        - kphotoalbum
        - lightdm
        - meld
        - ncdu
        - neofetch
        - net-tools
        - pipx
        - screenfetch
        - tree
        - unzip
        - vim
        - vlc
        - xz-utils
      when: 1 > 2

    - name: 3. Install python # Is this necessary??
      apt:
        name: python3
        update_cache: yes

    - name: 4. Install python packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - python3-pip
        - python3-yaml
        - python3-psutil
        - python3-jinja2

    - name: 5. Install python package
      ansible.builtin.pip:
        name: jinja2
      when: 1>2

    - name: 6. Install sound related packages # require reboot
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - pulseaudio
        - pavucontrol








