---
- name: install zoom
  hosts: wanted
  become: yes

  tasks:
    - name: multiple tools
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - curl
        - unzip
      when: 1 > 0

    - name: prepare zoom deb folder
      ansible.builtin.file:
        path: /home/robert/Downloads/zoom
        state: directory

    - name: download zoom file
      ansible.builtin.get_url:
        dest: /home/robert/Downloads/zoom
        url: https://zoom.us/client/6.2.3.2056/zoom_amd64.deb

    - name: prepare zoom2 deb folder
      ansible.builtin.file:
        path: /home/robert/Downloads/zoom2
        group: robert
        owner: robert
        mode: '777'
        state: directory

    - name: prepare dir for zoom deb file
      ansible.builtin.shell: |
        chdir /home/robert/Downloads/zoom2
        

    - name: download zoom file # https://community.zoom.com/t5/Zoom-Meetings/Installing-and-Upgrading-Zoom-desktop-client-on-Linux/td-p/82056
      ansible.builtin.get_url:
        dest: /home/robert/Downloads/zoom
        url: https://zoom.us/client/6.2.3.2056/zoom_amd64.deb

    - name: steps 2 + 3 + 4
      ansible.builtin.shell: |        
        wget -O package-signing-key.pub https://zoom.us/linux/download/pubkey?version=5-12-6
        gpg --show-keys package-signing-key.pub 
        gpg --import package-signing-key.pub

    - name: steps 5
      ansible.builtin.get_url:
        dest: /home/robert/Downloads/zoom2
        url: https://zoom.us/client/latest/zoom_amd64.deb
        group: robert
        owner: robert

    - name: steps 6 # apt install /home/robert/Downloads/zoom2/zoom_amd64.deb
      ansible.builtin.shell:
        cmd: dpkg -i /home/robert/Downloads/zoom2/zoom_amd64.deb

    - name: finale
      ansible.builtin.shell:
        cmd: ls /home/robert/Downloads



