---
- name: install zoom
  hosts: wanted
  become: yes
  vars_files:
    - vars.yml

  tasks:

    - name: 1. download zoom deb
      ansible.builtin.get_url:
        dest: "{{ simpli_dir }}/packages/"
        url: "{{ zoom_url }}"
        group: robert
        owner: robert

    - name: 2. install zoom deb # install the file
      ansible.builtin.apt:
        deb: "{{ simpli_dir }}/packages/{{zoom_deb}}"





