---
- name: install simpli tool suite
  hosts: wanted
  become: yes

  tasks:

    - name: 1. download zoom deb
      ansible.builtin.get_url:
        dest: /home/robert/.simpli/packages/
        url: https://zoom.us/client/latest/zoom_amd64.deb
        group: robert
        owner: robert

    - name: 2. install zoom deb # install the file
      ansible.builtin.apt:
        deb: /home/robert/.simpli/packages/zoom_amd64.deb





